In [1]:
import numpy as np


In [2]:
print([np.random.randint(0, 10, size=1, dtype=int) for _ in range(10)])

[array([9]), array([3]), array([4]), array([0]), array([8]), array([0]), array([5]), array([7]), array([4]), array([9])]


In [3]:
np.random.seed(0)
print([np.random.randint(0, 10, size=1, dtype=int) for _ in range(10)])

[array([5]), array([0]), array([3]), array([3]), array([7]), array([9]), array([3]), array([5]), array([2]), array([4])]


In [4]:
print([np.random.randint(0, 10, size=1, dtype=int) for _ in range(10)])

[array([7]), array([6]), array([8]), array([8]), array([1]), array([6]), array([7]), array([7]), array([8]), array([1])]


In [5]:
np.random.seed(0)
print([np.random.randint(0, 10, size=1, dtype=int) for _ in range(10)])
print([np.random.randint(0, 10, size=1, dtype=int) for _ in range(10)])

[array([5]), array([0]), array([3]), array([3]), array([7]), array([9]), array([3]), array([5]), array([2]), array([4])]
[array([7]), array([6]), array([8]), array([8]), array([1]), array([6]), array([7]), array([7]), array([8]), array([1])]


### i.e. as python random acts like iterator numpy dose same
### and once set random seed the iterator initialized

In [6]:
for i in range(3):
    np.random.seed(i)
    print(np.random.randint(0, 10, size=3, dtype=int))
    np.random.seed(i)
    print(np.random.randint(0, 10, size=5, dtype=int))
    print('*'*40)

[5 0 3]
[5 0 3 3 7]
****************************************
[5 8 9]
[5 8 9 5 0]
****************************************
[8 8 6]
[8 8 6 2 8]
****************************************


### Above block shows that for array, numpy fill the array as order

In [7]:
for i in range(2):
    np.random.seed(i)
    print(np.random.randn(2, 2))
    np.random.seed(i)
    print(np.random.randn(2, 4))
    print('*'*40)

[[1.76405235 0.40015721]
 [0.97873798 2.2408932 ]]
[[ 1.76405235  0.40015721  0.97873798  2.2408932 ]
 [ 1.86755799 -0.97727788  0.95008842 -0.15135721]]
****************************************
[[ 1.62434536 -0.61175641]
 [-0.52817175 -1.07296862]]
[[ 1.62434536 -0.61175641 -0.52817175 -1.07296862]
 [ 0.86540763 -2.3015387   1.74481176 -0.7612069 ]]
****************************************


## also for 2d array numpy fills as order  

In [8]:
for i in range(2):
    np.random.seed(i)
    print(np.random.randn(2, 2))
    print(np.random.randn(2, 2))
    np.random.seed(i)
    print(np.random.randn(2, 4))
    print('*'*40)

[[1.76405235 0.40015721]
 [0.97873798 2.2408932 ]]
[[ 1.86755799 -0.97727788]
 [ 0.95008842 -0.15135721]]
[[ 1.76405235  0.40015721  0.97873798  2.2408932 ]
 [ 1.86755799 -0.97727788  0.95008842 -0.15135721]]
[[ 1.62434536 -0.61175641]
 [-0.52817175 -1.07296862]]
[[ 0.86540763 -2.3015387 ]
 [ 1.74481176 -0.7612069 ]]
[[ 1.62434536 -0.61175641 -0.52817175 -1.07296862]
 [ 0.86540763 -2.3015387   1.74481176 -0.7612069 ]]


## However, one have to be caution
## Since when numpy fill the array along with aixs
## Thus, just concatnating the two 2X2 arrays is not equal to 2X4 or 4X2